version: '2.3'
services:
  training:
    image: pytorch/pytorch:1.5.1-cuda10.1-cudnn7-runtime
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=2,3,4,5
    user: "2004:2004"
    container_name: "moono_gpu_2345"
    volumes:
      - "/mnt/vision-nas/moono/git-repos/moco:/work-dir"
      - "/mnt/vision-nas/data-sets/cross_domain_faces:/dataset-dir:ro"
    working_dir: "/work-dir"
    command: ["python", "run_script.py"]
